name: "Snyk Python (3.11)"
description: "Check your Python application for vulnerabilties using Snyk"
author: "Gareth Rushgrove"
branding:
  icon: "alert-triangle"
  color: "yellow"
inputs:
  command:
    description: "Which Snyk command to run, defaults to test"
    default: test
  args:
    description: "Additional arguments to pass to Snyk"
  requirements-file:
    description: "Requirements file with python packages"
    default: requirements.txt
  json:
    description: "Output a snyk.json file with results if running the test command"
    default: false
runs:
  using: "docker"
  image: "docker://snyk/snyk:python-3.11"
  env:
    FORCE_COLOR: 2
    SNYK_INTEGRATION_NAME: GITHUB_ACTIONS
    SNYK_INTEGRATION_VERSION: python-3.11
    INPUT_REQUIREMENTS-FILE: ${{ inputs.requirements-file }}
    COMMAND: pip install -r ${{ inputs.requirements-file }}
  args:
  - snyk
  - ${{ inputs.command }}
  - ${{ inputs.args }}
